name: nf-test CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run nf-test in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Run nf-test in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            nextflow/nextflow:23.10.1 \
            bash -c "wget -qO- https://code.askimed.com/install/nf-test | bash && mv nf-test /usr/local/bin/ && nf-test test --coverage --verbose"

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: .nf-test/coverage/coverage.xml
          fail_ci_if_error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nf-test-results
          path: |
            .nf-test/
            !.nf-test/cache/
